language: java
dist: trusty
jdk:
  - oraclejdk8
  - openjdk8
  - openjdk7
  - openjdk6
install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -Dgpg.skip=true
addons:
  apt:
    packages:
      - openjdk-6-jdk
